---
- name: Collect IOS facts
  hosts: r1-ansible

  tasks:
  - name: Facts
    ios_facts:
      gather_subset: all
    register: ios_facts_result

  - name: Copy facts to files
    copy:
      content: "{{ ios_facts_result | to_nice_yaml }}"
      dest: "all_facts/{{inventory_hostname}}_facts.yml"
